### ISSUE TITLE
Style help pane

### ISSUE THREAD

**Issue by salim-b** [rileytwo/darkstudio#15]
I couldn't find any useful information on the topic by googling, so I thought I'd ask you since you seem to have quite some experience with RStudio's UI styling. 

**Is it possible to provide a custom stylesheet for RStudio's _help pane_?**

RStudio's current help pane styling is very minimal and looks almost the same for normal and `\code{}`-styled text – which is just sad IMHO. What I would really like is styling similar to how rdrr.io does it. Example for `?base::deparse`: https://rdrr.io/r/base/deparse.html

It's just so much more readable. 🤓

**Comment by rileytwo** [comment]
I've only been able to style the help pane within an `*.rstheme` file. From what I can tell with messing around in RStudio's DevTools, the issue lies in when `darkstudio.css` is loaded in relation to the help pane css files. You can try my [kiss theme](https://github.com/rileytwo/kiss.git), which modifies the font families/colors. Or, you can just take a look at the elements in the file for use in the theme of your choice. 

I think most of the elements can be altered, since (I think) they're exposed to the `R.css` file(s) packages are themed with.

**Comment by salim-b** [comment]
Ok, thanks for your tips! My CSS skills are pretty low and I have no experience with RStudio theming, but I'll see what I can achieve when I find some spare time.

**Comment by rileytwo** [comment]
[Here](https://github.com/rileytwo/kiss/blob/ec81f5b9326bc6d96606e61e25560ea2a5730b5a/rstudio/kiss.rstheme#L98-L121) are the lines from `kiss.rstheme` that style the help pane.

Snippet:

```css
/**
*
* Help Pane fonts
*
*/

/* #rstudio_workbench_panel_help * :-webkit-any(code) {
   font-family: var(--kiss-ui-monospace-font) !important;
 } */
/* .rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme p code, */
/* .rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme pre,  */
/* .rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme pre code, */
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme
  :-webkit-any(pre, code) {
  font-family: var(--kiss-ui-monospace-font) !important;
}

.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme p code {
  color: var(--kiss-help-monospace-font-fg) !important;
}

.rstudio-themes-flat.editor_dark.ace_editor_theme a {
  color: var(--kiss-cursor) !important;
}
```

You can ignore the commented lines--the `:-webkit-any()` should cover each element that's commented out.

You'll need to replace `var()` functions to the font-family/color you wish to use. For example, if you wanted to use Fira Code as the monospace font used in the help pane, you would change

```css
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme
  :-webkit-any(pre, code) {
  font-family: var(--kiss-ui-monospace-font) !important;
}
```

to

```css
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme
  :-webkit-any(pre, code) {
  font-family: Fira Code !important;
}
```

Obviously, you'll need to have the font installed for the help pane to actually use the font. This *should* work, but let me know if you run into any trouble.

**Comment by salim-b** [comment]
Hey @rileytwo 

Thanks again for your hints! Today I've spent some hours [creating a custom version of the _rscodeio_ theme](https://github.com/anthonynorth/rscodeio/pull/44) and finally managed to style the help pane according to my aesthetic feelings (largely inspired by GitHub CSS and the likes 😅).

The relevant rules look like this (feel free to adopt if you like):

```css
/* help pane */
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme p,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme h1,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme h2,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme h3,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme h4,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme h5,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme h6 {
  line-height: 1.75 !important;
  color: #DEDEDE !important;
}

.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme pre,
.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme code {
  font-family: "Fira Code", Ubuntu, "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
  font-size: 85%;
  color: white !important;
  background-color: #1A1A1A !important;
  border: 1px solid rgba(255,255,255,.1);
  border-radius: 3px;
}

.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme code {
  padding: .2em .4em;
}

.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme pre {
  padding: 1.5em;
  line-height: 1.45;
  overflow: auto;
}

.rstudio-themes-flat.rstudio-themes-dark.editor_dark.ace_editor_theme a {
  color: #80D7FF !important;
  text-decoration: none;
}
```

And the the result looks like this (for `?pal::as_string`):

![Bildschirmfoto von 2020-10-09 19-51-20](https://user-images.githubusercontent.com/20040931/95615784-51c1fe80-0a58-11eb-869f-8e8b90f668fc.png)
