### ISSUE TITLE
Background not dark on panels.

### ISSUE THREAD

**Issue by therimalaya** [rileytwo/darkstudio#6]
Nice job! The problems with the dialogue panels are still there. 

![image](https://user-images.githubusercontent.com/675384/57142573-22b45180-6dbd-11e9-9212-0c601127eddc.png)

I am using following RStudio,

![image](https://user-images.githubusercontent.com/675384/57142832-cbfb4780-6dbd-11e9-9879-87884626c09d.png)

**Comment by rileytwo** [comment]
UGH these menus are such a pane. I'm happy to help though.

A few things:

- What OS are you using? Windows? Linux?

- When did you install this RStudio version? I'm still on 1.2.15, so I haven't had a chance to test out anything past my current version.

**Comment by therimalaya** [comment]
Its version 1.2.127.  The second image will give some details. The os is MacOS Mojave.

**Comment by rileytwo** [comment]
The image says 1.3.127, right? Unless I'm seeing it wrong?

**Comment by therimalaya** [comment]
Yes, I'm sorry for misspelling.

**Comment by rileytwo** [comment]
No worries!

I don't have much time to work on this, so I've limited the scope of this project to RStudio-Preview and the version of RStudio that's on the master branch. I'm not able to keep up with the daily builds, so I'm not sure I can be of much help to you.

However, I can recommend you download RStudio-Preview and try the edits. It should work! 

RStudio-Preview link: https://www.rstudio.com/products/rstudio/download/preview/

Let me know if this helps and if you have any other questions. I'm going to close this since I don't support the daily builds.

**Comment by therimalaya** [comment]
Thank you, I just added three CSS rules in the `custom_css`, it has fixed those problems. These are the one I added,

```css
.GFUMY0GCEMB td.GFUMY0GCEMB {
        background-color: inherit;
}
.GFUMY0GCGK, .GFUMY0GCJ2, .GFUMY0GCI2 {
        background-color: inherit;
}
.GFUMY0GCLJ, .GFUMY0GCJ2 {
         background: #434343;
}
.GFUMY0GCGP .gwt-TabLayoutPanelTab {
        background-color: #323232;
}
```
